# Read the Docs configuration file for PDEVisualizer

version: 2

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

formats:
  - pdf
  - epub

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      - pip install --upgrade pip setuptools wheel
    post_install:
      - pip install -e ".[docs]"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs